#!/bin/sh
#
# SPDX-FileCopyrightText: 2020 Anuradha Weeraman <anuradha@weeraman.com>
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

basedir=$(dirname $(readlink -f $0))
. ${basedir}/config/env.sh

check_availability_of() {
	prog=$1
	if ! command -v ${prog} 2>&1 > /dev/null; then
		echo "$prog not found"
		exit 1
	fi
}

recreate_initrd_dir() {
  if [ -e "${initrd}" ]; then
    echo -n "Deleting existing initrd... "
    rm -rf ${initrd}
    rm -f ${basedir}/initramfs.cpio.gz
    echo "ok."
  fi

  echo -n "Creating initrd directory structure... "
  mkdir ${initrd} && cd ${initrd}
  mkdir -p bin sbin dev etc proc sys usr/bin usr/sbin
  cp ${confdir}/init ${initrd}/init
  chmod a+x ${initrd}/init
  echo "ok"
}

build_and_install_busybox() {
  if [ ! -e ${busyboxdir} ]; then
    echo -n "Cloning busybox... "
    mkdir -p ${busyboxdir}
    (
      cd ${depsdir}
      git clone --depth 1 --branch ${busybox_tag} \
	      git@github.com:mirror/busybox.git >> ${basedir}/log 2>&1
      if [ $? -ne 0 ]; then
        echo "failed."
      else
        echo "ok."
      fi
    )
  fi
  cp ${confdir}/busybox.config ${busyboxdir}/.config
  (
    cd ${busyboxdir}
    echo -n "Building busybox... "
    make -j${procs} >> ${basedir}/log 2>&1
    if [ $? -ne 0 ]; then
      echo "failed."
      exit 1
    else
      echo "ok."
    fi
    echo -n "Installing busybox... "
    make CONFIG_PREFIX=${initrd} install >> ${basedir}/log 2>&1
    if [ $? -ne 0 ]; then
      echo "failed."
      exit 1
    else
      echo "ok."
    fi
  )
}

check_availability_of git
check_availability_of make

recreate_initrd_dir
build_and_install_busybox

echo "Building initrd... "
(
  cd ${initrd}
  $(find . | cpio -oHnewc | gzip > ${basedir}/initramfs.cpio.gz) >> ${basedir}/log 2>&1
  if [ $? -ne 0 ]; then
    echo "failed."
    exit 1
  else
    echo "ok."
  fi
)
